# Generated by Django 4.1.13 on 2024-06-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('gender', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=50)),
                ('display_schedule', models.CharField(max_length=100)),
                ('subject_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=50)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slots', models.JSONField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='doctor.doctor')),
            ],
        ),
    ]
